In [2]:
import numpy as np
import matplotlib.pyplot as plt

x = np.array([[1.,2.,3.], 
              [4.,5.,6.]])

y = np.array([[6.,23.],
              [-1,7],
              [8,9]])

# matrix multiplication using numpy
x 


array([[1., 2., 3.],
       [4., 5., 6.]])

In [3]:
y 

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [ ]:
x.dot(y) # matrix multiplication
# or using the @ operator


array([[ 28.,  64.],
       [ 67., 181.]])

In [ ]:
x @ y # matrix multiplication   

array([[ 28.,  64.],
       [ 67., 181.]])

In [6]:
np.dot(x, y) # matrix multiplication
# or using the @ operator

array([[ 28.,  64.],
       [ 67., 181.]])

In [7]:
x @ np.ones(3) # matrix multiplication

array([ 6., 15.])

In [ ]:
from random import normalvariate    
rng = np.random.default_rng(seed=12345)






In [10]:
from numpy.linalg import inv, qr
# inverse of a matrix
X = rng.standard_normal((5, 5))
X 

array([[ 0.44948393, -1.34360107, -0.08168759,  1.72473993,  2.61815943],
       [ 0.77736134,  0.8286332 , -0.95898831, -1.20938829, -1.41229201],
       [ 0.54154683,  0.7519394 , -0.65876032, -1.22867499,  0.25755777],
       [ 0.31290292, -0.13081169,  1.26998312, -0.09296246, -0.06615089],
       [-1.10821447,  0.13595685,  1.34707776,  0.06114402,  0.0709146 ]])

In [11]:
mat = X.T @ X # make it symmetric positive-definite
inv(mat) # inverse of a matrix

array([[ 12.32597814,  48.47078428,   4.7395685 ,  33.31917729,
          1.53071665],
       [ 48.47078428, 204.12279205,  18.52724649, 139.4197772 ,
          7.24368453],
       [  4.7395685 ,  18.52724649,   2.07089433,  12.60432674,
          0.64333227],
       [ 33.31917729, 139.4197772 ,  12.60432674,  95.85084362,
          4.53620833],
       [  1.53071665,   7.24368453,   0.64333227,   4.53620833,
          0.64593751]])

In [12]:
mat @ inv(mat) # identity matrix
# QR decomposition


array([[ 1.00000000e+00, -1.26539346e-14,  1.01405894e-15,
        -1.45787873e-15, -3.95760973e-16],
       [-2.44514270e-14,  1.00000000e+00, -4.17453024e-15,
         2.78165026e-15,  5.30822797e-15],
       [ 4.21759538e-15,  7.25983678e-15,  1.00000000e+00,
        -1.64897034e-15, -6.87413062e-16],
       [ 2.38766152e-15, -1.54521884e-13, -1.05086545e-14,
         1.00000000e+00, -1.02069303e-14],
       [ 4.40087386e-14,  1.75039100e-13,  2.46144353e-14,
         1.62189363e-13,  1.00000000e+00]])