In [1]:
# 4.5 File Input and Output with Arrays

import numpy as np
import matplotlib.pyplot as plt
import os
import sys

arr = np.arange(10)
np.save('my_array.npy', arr)
arr2 = np.load('my_array.npy')




In [2]:
arr2  # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Save the array to a text file

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.savez('my_array_archive.npz', a=arr, b=arr2)
# Load the array from the text file
arch = np.load('my_array_archive.npz')
arch.files  # ['a', 'b']



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arch['a']  # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arch['b'] # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.savez_compressed('my_array_archive_compressed.npz', a=arr, b=arr2)
# Load the array from the compressed text file
arch_comp = np.load('my_array_archive_compressed.npz')


In [10]:
arch_comp = np.load('my_array_archive_compressed.npz')
arch_comp.files  # ['a', 'b']

['a', 'b']