In [2]:
import numpy as np

arr = np.array([[1., 2., 3.],[4., 5., 6.]])
arr 

array([[1., 2., 3.],
       [4., 5., 6.]])

In [3]:
arr*arr
# Output: array([[ 1.,  4.,  9.],
#                [16., 25., 36.]])
# Element-wise multiplication of the array with itself


array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [4]:
arr-arr
# Output: array([[0., 0., 0.],
#                [0., 0., 0.]])
# Element-wise subtraction of the array from itself


array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
1/arr
# Output: array([[1.        , 0.5       , 0.33333333],
#                [0.25      , 0.2       , 0.16666667]])
# Element-wise division of 1 by the array elements

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [6]:
arr**2
# Output: array([[ 1.,  4.,  9.],
#                [16., 25., 36.]])
# Element-wise exponentiation of the array elements to the power of 2


array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [7]:
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr2
# Output: array([[ 0.,  4.,  1.],
#                [ 7.,  2., 12.]])
# Second array for element-wise operations
# Element-wise addition of two arrays    


array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [ ]:
arr2 > arr
# Output: array([[False, False, False],
#                [ True, False,  True]])
# Element-wise comparison of two arrays
