In [2]:
import numpy as np
#import matplotlib.pyplot as plt

arr = np.arange(10)
arr  

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[5]    # 5 

np.int64(5)

In [4]:

arr[5:8]  # array([5, 6, 7])

array([5, 6, 7])

In [5]:
arr[5:8] = 12  # set values in the slice to 12
arr  # array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])


array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [6]:
arr_slice = arr[5:8]  # create a slice of the array  
arr 

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [7]:
arr_slice[2] = 2608 # set the last value of the slice to 2608
arr  # array([ 0,  1,  2,  3,  4, 12, 12, 2608,  8,  9]) 
# The original array is modified when the slice is modified
# This is because the slice is a view of the original array, not a copy


array([   0,    1,    2,    3,    4,   12,   12, 2608,    8,    9])

In [8]:
arr_slice[:] = 64 # set all values in the slice to 64
arr  # array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [9]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]   # array([7, 8, 9]) 

array([7, 8, 9])

In [10]:
arr2d[0][2] # 3

np.int64(3)

In [11]:
arr2d[0, 2] # 3


np.int64(3)

In [12]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d   # array([[1, 2, 3], [4, 5, 6]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [13]:
arr3d[0]  # array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr3d[0][1]  # array([4, 5, 6])

array([4, 5, 6])

In [15]:
arr3d[1 , 0]  # array([7, 8, 9])


array([7, 8, 9])

In [16]:
arr3d[1]  # array([[ 7,  8,  9], [10, 11, 12]]) 

array([[ 7,  8,  9],
       [10, 11, 12]])

In [17]:
arr3d[1,1]  # array([10, 11, 12])

array([10, 11, 12])

In [18]:
arr3d[1,1,0] # 10

np.int64(10)

In [19]:
old_value = arr3d[0].copy()  # create a copy of the first slice
arr3d[0] = 42  # set the first slice to 42
arr3d  # array([[42, 42, 42], [42, 42, 42]])

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
arr3d[0] = old_value  # restore the original value
arr3d  # array([[1, 2, 3], [4, 5, 6]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [21]:
x = arr3d[1]  # array([[ 7,  8,  9], [10, 11, 12]])
x # array([[ 7,  8,  9], [10, 11, 12]])

array([[ 7,  8,  9],
       [10, 11, 12]])

In [22]:
x[0]  # array([7, 8, 9])

array([7, 8, 9])

In [23]:
arr # array([[1, 2, 3], [4, 5, 6]])

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [24]:
arr2d  # array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr2d[:2]   # array([[1, 2, 3], [4, 5, 6]])


array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr2d[:2, 1:]  # array([[2, 3], [5, 6]])

array([[2, 3],
       [5, 6]])

In [28]:
lower_dim_slice = arr2d[1, 1:]  # array([5, 6])
lower_dim_slice.shape  # (2,)

(2,)

In [29]:
arr2d[:2, 2] # array([[3], [6]])

array([3, 6])

In [30]:
arr2d[:, :1] # array([[1], [4], [7]])

array([[1],
       [4],
       [7]])

In [ ]:
arr2d[:2, 1:] = 0  # set the last two columns of the first two rows to 0

arr2d # array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])