In [57]:
import numpy as np
data = np.array([[1.5,-0.1,3],[0,-3,6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [58]:
data*10


array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [59]:
data.shape


(2, 3)

In [60]:
data.dtype

dtype('float64')

In [61]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [62]:
data2 =[[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [63]:
arr2.ndim
arr2.shape

(2, 4)

In [64]:
arr2.ndim

2

In [65]:
arr1.dtype

dtype('float64')

In [66]:
arr2.dtype

dtype('int64')

In [67]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [68]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [69]:
np.empty((2, 3, 2))     # 2x3x2 array filled with random numbers
                        # 2x3 matrix with 2 elements in each cell
                      

array([[[1.38287103e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.11260619e-306, 4.08467983e+179]],

       [[1.45216860e-047, 7.31507018e-042],
        [1.84744572e+184, 8.70407797e-071],
        [1.53540176e-075, 1.47762850e+185]]])

In [70]:
np.arange(15)  # 0 to 14  

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [71]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([4,5,6], dtype=np.int32)
arr1.dtype, arr2.dtype

(dtype('float64'), dtype('int32'))

In [72]:
arr = np.array([1,2,3,4,5])
arr.dtype  

dtype('int64')

In [73]:
float_arr = arr.astype(np.float64)
float_arr 

array([1., 2., 3., 4., 5.])

In [74]:
float_arr.dtype

dtype('float64')

In [75]:
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])
arr
 

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [76]:
arr = arr.astype(np.int32)
arr

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [ ]:
numeric_string = np.array(['1.25', '-9.6', '42'], dtype=np.bytes_)
numeric_string.astype(float)
# np.string_ is the default string type; np.bytes_ is a byte string type
# np.unicode_ is a unicode string type

array([ 1.25, -9.6 , 42.  ])

In [81]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .38, .44, .45], dtype=np.float64)
int_array.astype(calibers.dtype)  # int_array is converted to calibers' type


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
zeros_uint = np.zeros(8, dtype='u4')  # unsigned int of 4 bytes-uint32
zeros_uint

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)