In [1]:
import numpy as np

names = np.array(["Ning", "Yelan", "Ei","Ei", "Kuki", "Yae",
                  " Fischl"])
data = np.array([[26,8],[10,4],[26,6],[-6,-26],[-27,9],[27,6],[2,12]])
names  # 2D array of names    

array(['Ning', 'Yelan', 'Ei', 'Ei', 'Kuki', 'Yae', ' Fischl'], dtype='<U7')

In [2]:
data  # 2D array of data
 # 2D array of data with names as rows
 

array([[ 26,   8],
       [ 10,   4],
       [ 26,   6],
       [ -6, -26],
       [-27,   9],
       [ 27,   6],
       [  2,  12]])

In [3]:
names == "Ei" # boolean array where names are "Ei"

array([False, False,  True,  True, False, False, False])

In [4]:
data[names == "Ei"]  # data for "Ei"

array([[ 26,   6],
       [ -6, -26]])

In [5]:
data[ names == "Ei", :]  # data for "Ei" with all columns

array([[ 26,   6],
       [ -6, -26]])

In [6]:
data[names == "Ei", 1:]   
# data for "Ei" with all columns except the first

array([[  6],
       [-26]])

In [7]:
data[names == "Ei", 1]   
# data for "Ei" with the second column only

array([  6, -26])

In [8]:
names != "Ei"  # boolean array where names are not "Ei"



array([ True,  True, False, False,  True,  True,  True])

In [9]:
~(names == "Ei")  # boolean array where names are not "Ei"



array([ True,  True, False, False,  True,  True,  True])

In [10]:
data[~(names == "Ei")] # data for names that are not "Ei"

array([[ 26,   8],
       [ 10,   4],
       [-27,   9],
       [ 27,   6],
       [  2,  12]])

In [11]:
mask = (names == "Ei") | (names == "Ning")    # boolean mask for "Ei"
mask # boolean mask for "Ei" and "Ning" 
     

array([ True, False,  True,  True, False, False, False])

In [12]:
data[mask] # data for "Ei" and "Ning"

array([[ 26,   8],
       [ 26,   6],
       [ -6, -26]])

In [13]:
data[data<0] = 0  # set negative values to 0
data # data with negative values set to 0

array([[26,  8],
       [10,  4],
       [26,  6],
       [ 0,  0],
       [ 0,  9],
       [27,  6],
       [ 2, 12]])

In [14]:
data[names != "Ei"] = 8 
# set data for names that are not "Ei" to 8
data # data with names that are not "Ei" set to 8


array([[ 8,  8],
       [ 8,  8],
       [26,  6],
       [ 0,  0],
       [ 8,  8],
       [ 8,  8],
       [ 8,  8]])

In [15]:
# Fancy indexing
# Fancy indexing is a way to access multiple elements of an array using an array of indices 

arr = np.zeros((8,4)) # create a 2D array of zeros
for i in range(8):
    arr[i] = i  # set each row to the index value
arr # 2D array of zeros with each row set to the index value

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [16]:
arr[[4,3,0,6]] # access rows 4, 3, 0, and 6

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [17]:
arr[[-3,-5,-7]] # access rows -3, -5, and -7
# The negative indices count from the end of the array 

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [18]:
arr = np.arange(32).reshape((8,4)) # create a 2D array of 32 elements
arr # 2D array of 32 elements

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [ ]:
arr[[1,5,7,2],[0,3,1,2]] # access specific elements using row and column indices
# The first index is the row index and the second index is the column index         

array([ 4, 23, 29, 10])

In [ ]:
arr[[1,5,7,2]][:, [0,3,1,2]]  # access specific elements using row and column indices
# The first index is the row index and the second index is the column index

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [24]:
arr[[1,5,7,2],[0,3,1,2]] # access specific elements using row and column indices

array([ 4, 23, 29, 10])

In [25]:
arr[[1,5,7,2],[0,3,1,2]]=0  # set specific elements to 0
arr # 2D array with specific elements set to 0

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

In [26]:
# Transposing arrays and Swapping axes
# Transposing arrays is a way to change the shape of an array by swapping its axes
# Swapping axes is a way to change the order of the axes of an array

arr = np.arange(15).reshape((3,5)) # create a 2D array of 15 elements
arr # 2D array of 15 elements

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
arr.T # transpose the array
# The transpose of an array is obtained by swapping its axes

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [28]:
arr = np.array([[0,1,0],[1,2,-2],[6,3,2],[-1,0,-1],[1,0,1]]) 
# create a 2D array of 15 elements  
arr # 2D array of 15 elements

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [29]:
np.dot(arr.T, arr) # dot product of the transposed array and the original array
# The dot product of two arrays is obtained by multiplying the corresponding elements and summing them up

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [30]:
arr.T @ arr # dot product of the transposed array and the original array
# The dot product of two arrays is obtained by multiplying the corresponding elements and summing them up

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [31]:
arr  # 2D array of 15 elements


array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [ ]:
arr.swapaxes(0,1) # swap the axes of the array
# The swapaxes method is used to swap the axes of an array
