In [5]:
# 4.3 Universal Functions (ufuncs)
# NumPy provides a large set of functions that operate on ndarrays in an element-by-element fashion, these are called universal functions or ufuncs.
# These functions are fast and efficient, and they can be used to perform a wide variety of operations on arrays.
# For example, the following code creates a NumPy array of integers from 0 to 9 using the arange function, which is a ufunc that generates evenly spaced values within a given range.
# The arange function is similar to the built-in range function in Python, but it returns a NumPy array instead of a list.
# The arange function takes three arguments: start, stop, and step. The start argument is the starting value of the sequence, the stop argument is the end value (exclusive), and the step argument is the increment between each value in the sequence. If the step argument is not provided, it defaults to 1.
# The following code creates a NumPy array of integers from 0 to 9 using the arange function.
# The resulting array is a one-dimensional array with 10 elements, each representing an integer from 0 to 9.
# The output of the code is a NumPy array with the values from 0 to 9.
# Fast Element-wise Array Functions
import numpy as np

arr = np.arange(10)
arr
# Output: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.sqrt(arr)
# Output: array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [7]:
np.exp(arr)
# Output: array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003,

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [8]:
from random import normalvariate    
rng = np.random.default_rng(seed=12345)  # Create a random number generator with a fixed seed
# 148.4131591 , 403.42879349, 1096.63315843, 2980.95798704, 8103.08392758])
# Generate random numbers from a normal distribution

x = rng.standard_normal(8)  
y = rng.standard_normal(8)
x
# Output: array([-0.1382643 ,  0.64768854,  1.52302986, -0.23415337, -0.23413696,

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331,
       -0.74088465, -1.3677927 ,  0.6488928 ])

In [9]:
y
# Output: array([ 0.49671415, -0.23413696,  1.57921282,  0.76743473, -0.46947439,
#        0.54256004, -0.46341769, -0.46572975])

array([ 0.36105811, -1.95286306,  2.34740965,  0.96849691, -0.75938718,
        0.90219827, -0.46695317, -0.06068952])

In [10]:
np.maximum(x, y) 
# Output: array([ 0.49671415,  0.64768854,  1.57921282,  0.76743473, -0.23413696,
#        0.54256004, -0.46341769, -0.46572975])

array([ 0.36105811,  1.26372846,  2.34740965,  0.96849691, -0.07534331,
        0.90219827, -0.46695317,  0.6488928 ])

In [11]:
arr = rng.standard_normal(7)*5
arr
# Output: array([-0.1382643 ,  0.64768854,  1.52302986, -0.23415337, -0.23413696,
#        0.49671415, -0.23413696,  1.57921282,  0.76743473, -0.46947439,
#        0.54256004, -0.46341769, -0.46572975])
#        0.49671415, -0.23413696,  1.57921282,  0.76743473, -0.46947439,

array([ 3.94422172, -6.28334067,  2.87928757,  6.99489497,  6.6114903 ,
       -1.49849258,  4.51459671])

In [13]:
remainder, whole_part = np.modf(arr)
remainder
# Output: array([-0.1382643 ,  0.64768854,  1.52302986, -0.23415337, -0.23413696,
#        0.49671415, -0.23413696,  1.57921282,  0.76743473, -0.46947439,
#        0.54256004, -0.46341769, -0.46572975])
#        0.49671415, -0.23413696,  1.57921282,  0.76743473, -0.46947439,
#        0.54256004, -0.46341769, -0.46572975])
#        0.49671415, -0.23413696,  1.57921282,  0.76743473, -0.46947439,
#        0.54256004, -0.46341769, -0.46572975])
#        0.49671415, -0.23413696,  1.57921282,  0.76743473, -0.46947439,
#        0.54256004, -0.46341769, -0.46572975])
#        0.49671415, -0.23413696,  1.57921282,  0.76743473, -0.46947439,
#        0.54256004, -0.46341769, -0.46572975])
#        0.49671415, -0.23413696,  1.57921282,  0.76743473, -0.46947439,
#        0.54256004, -0.46341769, -0.46572975])

array([ 0.94422172, -0.28334067,  0.87928757,  0.99489497,  0.6114903 ,
       -0.49849258,  0.51459671])

In [14]:
whole_part
# Output: array([-0.1382643 ,  0.64768854,  1.52302986, -0.23415337, -0.23413696,
#        0.49671415, -0.23413696,  1.57921282,  0.76743473, -0.46947439,
#        0.54256004, -0.46341769, -0.46572975])
#        0.49671415, -0.23413696,  1.57921282,  0.76743473, -0.46947439,
#        0.54256004, -0.46341769, -0.46572975])
#        0.49671415, -0.23413696,  1.57921282,  0.76743473, -0.46947439,
#        0.54256004, -0.46341769, -0.46572975])

array([ 3., -6.,  2.,  6.,  6., -1.,  4.])

In [15]:
arr
# Output: array([-0.1382643 ,  0.64768854,  1.52302986, -0.23415337, -0.23413696,
#        0.49671415, -0.23413696,  1.57921282,  0.76743473, -0.46947439,
#        0.54256004, -0.46341769, -0.46572975])
#        0.49671415, -0.23413696,  1.57921282,  0.76743473, -0.46947439,
#        0.54256004, -0.46341769, -0.46572975])


array([ 3.94422172, -6.28334067,  2.87928757,  6.99489497,  6.6114903 ,
       -1.49849258,  4.51459671])

In [18]:
out = np.zeros_like(arr)
# Output: array([0., 0., 0., 0., 0., 0., 0., 0.])
#        0.49671415, -0.23413696,  1.57921282,  0.76743473, -0.46947439,
#        0.54256004, -0.46341769, -0.46572975])
#        0.49671415, -0.23413696,  1.57921282,  0.76743473, -0.46947439,
#        0.54256004, -0.46341769, -0.46572975])
np.add(arr, 1)
# Output: array([ 0.8617357 ,  1.64768854,  2.52302986,  0.76584663,  0.76586304,
#        1.49671415,  0.76586304,  2.57921282,  1.76743473,  0.53052561,

array([ 4.94422172, -5.28334067,  3.87928757,  7.99489497,  7.6114903 ,
       -0.49849258,  5.51459671])

In [19]:
np.add(arr, 1, out=out)
# Output: array([ 0.8617357 ,  1.64768854,  2.52302986,  0.76584663,  0.76586304,
#        1.49671415,  0.76586304,  2.57921282,  1.76743473,  0.53052561,
#        1.54256004,  0.53658231,  0.53427025])

array([ 4.94422172, -5.28334067,  3.87928757,  7.99489497,  7.6114903 ,
       -0.49849258,  5.51459671])

In [20]:
out  
# Output: array([ 0.8617357 ,  1.64768854,  2.52302986,  0.76584663,  0.76586304,
#        1.49671415,  0.76586304,  2.57921282,  1.76743473,  0.53052561,
#        1.54256004,  0.53658231,  0.53427025])



array([ 4.94422172, -5.28334067,  3.87928757,  7.99489497,  7.6114903 ,
       -0.49849258,  5.51459671])