In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


s1 = pd.Series([7.3, -2.5, 3.4, 1.5], 
               index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], 
               index=['a', 'c', 'e', 'f', 'g'])




In [3]:
s1,s2
# Series addition

(a    7.3
 c   -2.5
 d    3.4
 e    1.5
 dtype: float64,
 a   -2.1
 c    3.6
 e   -1.5
 f    4.0
 g    3.1
 dtype: float64)

In [4]:
s1 + s2
# Series subtraction

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [5]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), 
                        columns= list('bcd'), 
                        index=['Mondstadt', 'Liyue', 'Inazuma'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), 
                        columns= list('bde'), 
                        index=['Sumeru', 'Mondstadt', 'Liyue', 'Khaenria'])



In [6]:
df1, df2
# DataFrame addition

(             b    c    d
 Mondstadt  0.0  1.0  2.0
 Liyue      3.0  4.0  5.0
 Inazuma    6.0  7.0  8.0,
              b     d     e
 Sumeru     0.0   1.0   2.0
 Mondstadt  3.0   4.0   5.0
 Liyue      6.0   7.0   8.0
 Khaenria   9.0  10.0  11.0)

In [7]:
df1 + df2 


b   c     d   e
Inazuma    NaN NaN   NaN NaN
Khaenria   NaN NaN   NaN NaN
Liyue      9.0 NaN  12.0 NaN
Mondstadt  3.0 NaN   6.0 NaN
Sumeru     NaN NaN   NaN NaN

In [8]:
df1 = pd.DataFrame({"A":[1, 2]})
df2 = pd.DataFrame({"B":[3, 4]})


In [9]:
df1,df2
# DataFrame concatenation

(   A
 0  1
 1  2,
    B
 0  3
 1  4)

In [10]:
# Concatenate along the index (axis=0)
df1+df2     
# This will raise an error because the DataFrames have different columns


A   B
0 NaN NaN
1 NaN NaN

In [11]:
# Arithmetic methods with fill values

df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                        columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                        columns=list('abcde'))
df1, df2
# DataFrame addition with fill values

(     a    b     c     d
 0  0.0  1.0   2.0   3.0
 1  4.0  5.0   6.0   7.0
 2  8.0  9.0  10.0  11.0,
       a     b     c     d     e
 0   0.0   1.0   2.0   3.0   4.0
 1   5.0   6.0   7.0   8.0   9.0
 2  10.0  11.0  12.0  13.0  14.0
 3  15.0  16.0  17.0  18.0  19.0)

In [12]:
df2.loc[1, "b"] = np.nan

df1



a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [13]:

df2 


a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [14]:
df1 + df2
# DataFrame addition with fill values


a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [15]:
df1.add(df2, fill_value=0) 

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [16]:
1/df1
# Division by a DataFrame

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [17]:
df1.rdiv(1)
# Reverse division by a DataFrame


a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [18]:
df1.reindex(columns=df2.columns, fill_value=0)
# Reindexing with fill values


a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [19]:
# Operations between DataFrame and Series

arr = np.arange(12.).reshape((3, 4))

arr
# DataFrame with a Series

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [20]:
arr[0]
# Series with a DataFrame

array([0., 1., 2., 3.])

In [21]:
arr - arr[0]
# Broadcasting a Series across a DataFrame

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [22]:
arr + arr[0]
# Broadcasting a Series across a DataFrame

array([[ 0.,  2.,  4.,  6.],
       [ 4.,  6.,  8., 10.],
       [ 8., 10., 12., 14.]])

In [23]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                        columns=list('bde'), 
                        index=['Sumeru', 'Mondstadt', 'Liyue', 'Khaenria']) 

series = frame.iloc[0]
series_a = frame.iloc[0].copy()
series1 = frame.iloc[1]
series2 = frame.iloc[2]
series3 = frame.iloc[3]
frame

b     d     e
Sumeru     0.0   1.0   2.0
Mondstadt  3.0   4.0   5.0
Liyue      6.0   7.0   8.0
Khaenria   9.0  10.0  11.0

In [24]:
series
# Series with a DataFrame

b    0.0
d    1.0
e    2.0
Name: Sumeru, dtype: float64

In [25]:
series_a    
# Series with a DataFrame

b    0.0
d    1.0
e    2.0
Name: Sumeru, dtype: float64

In [26]:
series1


b    3.0
d    4.0
e    5.0
Name: Mondstadt, dtype: float64

In [27]:
series2


b    6.0
d    7.0
e    8.0
Name: Liyue, dtype: float64

In [28]:
series3


b     9.0
d    10.0
e    11.0
Name: Khaenria, dtype: float64

In [29]:
frame - series



b    d    e
Sumeru     0.0  0.0  0.0
Mondstadt  3.0  3.0  3.0
Liyue      6.0  6.0  6.0
Khaenria   9.0  9.0  9.0

In [30]:
c_series = pd.Series(np.arange(3), index=['b','e','f'])

c_series


b    0
e    1
f    2
dtype: int64

In [31]:
frame + c_series


b   d     e   f
Sumeru     0.0 NaN   3.0 NaN
Mondstadt  3.0 NaN   6.0 NaN
Liyue      6.0 NaN   9.0 NaN
Khaenria   9.0 NaN  12.0 NaN

In [32]:
d_series = frame['d']

frame


b     d     e
Sumeru     0.0   1.0   2.0
Mondstadt  3.0   4.0   5.0
Liyue      6.0   7.0   8.0
Khaenria   9.0  10.0  11.0

In [33]:
d_series


Sumeru        1.0
Mondstadt     4.0
Liyue         7.0
Khaenria     10.0
Name: d, dtype: float64

In [ ]:
frame.sub(d_series, axis='index')


b    d    e
Sumeru    -1.0  0.0  1.0
Mondstadt -1.0  0.0  1.0
Liyue     -1.0  0.0  1.0
Khaenria  -1.0  0.0  1.0