In [1]:
# Chapter 12 - Introduction to Modeling Libraries in Python

In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt 


In [3]:
data = pd.DataFrame({
       'x0': [1, 2, 3, 4, 5],
       'x1': [0.01, -0.01, 0.25, -4.1, 0.],
       'y': [-1.5, 0., 3.6, 1.3, -2.]
})

data

x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [4]:
data.columns

Index(['x0', 'x1', 'y'], dtype='object')

In [5]:
data.to_numpy()

# Turning Dataframe into a Numpy array

array([[ 1.  ,  0.01, -1.5 ],
       [ 2.  , -0.01,  0.  ],
       [ 3.  ,  0.25,  3.6 ],
       [ 4.  , -4.1 ,  1.3 ],
       [ 5.  ,  0.  , -2.  ]])

In [6]:
df2 = pd.DataFrame(data.to_numpy(),
                   columns=['one', 'two', 'three'])

df2

# To convert back a Dataframe

one   two  three
0  1.0  0.01   -1.5
1  2.0 -0.01    0.0
2  3.0  0.25    3.6
3  4.0 -4.10    1.3
4  5.0  0.00   -2.0

In [7]:
df3 = data.copy()

df3['strings'] = ['a', 'b', 'c', 'd', 'e']

In [8]:
df3

x0    x1    y strings
0   1  0.01 -1.5       a
1   2 -0.01  0.0       b
2   3  0.25  3.6       c
3   4 -4.10  1.3       d
4   5  0.00 -2.0       e

In [9]:
df3.to_numpy()

array([[1, 0.01, -1.5, 'a'],
       [2, -0.01, 0.0, 'b'],
       [3, 0.25, 3.6, 'c'],
       [4, -4.1, 1.3, 'd'],
       [5, 0.0, -2.0, 'e']], dtype=object)

In [10]:
model_cols = ['x0', 'x1']

data.loc[:, model_cols].to_numpy()

# how to subset of the columns using loc

array([[ 1.  ,  0.01],
       [ 2.  , -0.01],
       [ 3.  ,  0.25],
       [ 4.  , -4.1 ],
       [ 5.  ,  0.  ]])

In [11]:
data['category'] = pd.Categorical(['amber', 'barbara', 'amber', 'amber', 'barbara'],
                                  categories=['amber', 'barbara'])

data


x0    x1    y category
0   1  0.01 -1.5    amber
1   2 -0.01  0.0  barbara
2   3  0.25  3.6    amber
3   4 -4.10  1.3    amber
4   5  0.00 -2.0  barbara

In [12]:
dummies = pd.get_dummies(data.category, prefix='category')

data_with_dummies = data.drop('category', axis=1).join(dummies)

In [13]:
data_with_dummies

x0    x1    y  category_amber  category_barbara
0   1  0.01 -1.5            True             False
1   2 -0.01  0.0           False              True
2   3  0.25  3.6            True             False
3   4 -4.10  1.3            True             False
4   5  0.00 -2.0           False              True

In [14]:
# 12.2 Creating Model Descriptions with Patsy
# It is a Library for describing statistical models (sep.ly linear models) 
# with a string-based "formula syntax". Which is insoired by 
# the R and S programming languages

# Patsy is well supported for specifying linear models in statmodels, 
# so focusing on some of the main features to help get up and running

# Patsy formulas are special string syntax looks like : y ~ x0 + x1

# The syntax a = b does not mean to add a to b, but 
# rather that these are terms in the design matrix created for the model

In [15]:
data = pd.DataFrame({
    'x0': [1, 2, 3, 4, 5],
    'x1': [0.01, -0.01, 0.25, -4.1, 0.],
    'y': [-1.5, 0., 3.6, 1.3, -2.]
})

data 

x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [16]:
import patsy

y, x = patsy.dmatrices('y ~ x0 + x1', data)

y

DesignMatrix with shape (5, 1)
     y
  -1.5
   0.0
   3.6
   1.3
  -2.0
  Terms:
    'y' (column 0)

In [17]:
x

DesignMatrix with shape (5, 3)
  Intercept  x0     x1
          1   1   0.01
          1   2  -0.01
          1   3   0.25
          1   4  -4.10
          1   5   0.00
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'x1' (column 2)

In [18]:
np.array(y)

array([[-1.5],
       [ 0. ],
       [ 3.6],
       [ 1.3],
       [-2. ]])

In [19]:
np.array(x)

array([[ 1.  ,  1.  ,  0.01],
       [ 1.  ,  2.  , -0.01],
       [ 1.  ,  3.  ,  0.25],
       [ 1.  ,  4.  , -4.1 ],
       [ 1.  ,  5.  ,  0.  ]])

In [20]:
np.asarray(y)

array([[-1.5],
       [ 0. ],
       [ 3.6],
       [ 1.3],
       [-2. ]])

In [21]:
np.asarray(x)

array([[ 1.  ,  1.  ,  0.01],
       [ 1.  ,  2.  , -0.01],
       [ 1.  ,  3.  ,  0.25],
       [ 1.  ,  4.  , -4.1 ],
       [ 1.  ,  5.  ,  0.  ]])

In [22]:
patsy.dmatrices('y ~ x0 + x1 + 0', data)[1]

DesignMatrix with shape (5, 2)
  x0     x1
   1   0.01
   2  -0.01
   3   0.25
   4  -4.10
   5   0.00
  Terms:
    'x0' (column 0)
    'x1' (column 1)

In [23]:
coef, resid, _,_ = np.linalg.lstsq(x, y)

coef

# it can be passed directly into algorithms like 
# numpy.linalg.lstsq - which performs an ordinary least squares regressions

array([[ 0.31290976],
       [-0.07910564],
       [-0.26546384]])

In [24]:
coef = pd.Series(coef.squeeze(), 
                 index=x.design_info.column_names)

coef

# The model metadata is retained in the design_info attribute, 
# so you can reattach the model column names to the fitted coefficients 
# to obtain a Series

Intercept    0.312910
x0          -0.079106
x1          -0.265464
dtype: float64

In [25]:
# Data Transformations in Patsy Formulas

# You can mix py code into your patsy formulas, when evaluating the formula,
# the library will try to find the functions you use in the enclosing scope

In [26]:
y, x = patsy.dmatrices('y ~ x0 + np.log(np.abs(x1) + 1)', data)

x

DesignMatrix with shape (5, 3)
  Intercept  x0  np.log(np.abs(x1) + 1)
          1   1                 0.00995
          1   2                 0.00995
          1   3                 0.22314
          1   4                 1.62924
          1   5                 0.00000
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'np.log(np.abs(x1) + 1)' (column 2)

In [27]:
y, X = patsy.dmatrices('y ~ standardize(x0) + center(x1)', data)

X

DesignMatrix with shape (5, 3)
  Intercept  standardize(x0)  center(x1)
          1         -1.41421        0.78
          1         -0.70711        0.76
          1          0.00000        1.02
          1          0.70711       -3.33
          1          1.41421        0.77
  Terms:
    'Intercept' (column 0)
    'standardize(x0)' (column 1)
    'center(x1)' (column 2)

In [28]:
new_data = pd.DataFrame({
    'x0' : [6, 7, 8, 9],
    'x1' : [3.1, -0.5, 0, 2.3],
    'y' :  [1, 2, 3, 4]
})

In [29]:
new_x = patsy.build_design_matrices([X.design_info], new_data)

new_x

[DesignMatrix with shape (4, 3)
   Intercept  standardize(x0)  center(x1)
           1          2.12132        3.87
           1          2.82843        0.27
           1          3.53553        0.77
           1          4.24264        3.07
   Terms:
     'Intercept' (column 0)
     'standardize(x0)' (column 1)
     'center(x1)' (column 2)]

In [30]:
y, X = patsy.dmatrices('y ~ I(x0 + x1)', data)

X

# Because some symbols (+) in the context of the Patsy formula are not 
# valid Python syntax,
# we need to use the `I()` function to indicate that 
# we want to include the sum as a single term.
# also does not mean addition

DesignMatrix with shape (5, 2)
  Intercept  I(x0 + x1)
          1        1.01
          1        1.99
          1        3.25
          1       -0.10
          1        5.00
  Terms:
    'Intercept' (column 0)
    'I(x0 + x1)' (column 1)

In [31]:
# Categorical Data and Patsy

data = pd.DataFrame({
    'key1': ['a', 'a', 'b', 'b', 'a', 'b', 'a', 'b'],
    'key2': [0, 1, 0, 1, 0, 1, 0, 0],
    'v1': [1,2,3,4,5,6,7,8],
    'v2': [-1, 0, 2.5, -0.5, 4.0, -1.2, 0.2, -1.7]
})

In [32]:
y, X = patsy.dmatrices('v2 ~ key1', data)

In [33]:
X

# Non Numeric Data can be represented using Categorical Variables
# Categorical Variables can be created using the `C()` function in Patsy
# Example: C(key1)

DesignMatrix with shape (8, 2)
  Intercept  key1[T.b]
          1          0
          1          0
          1          1
          1          1
          1          0
          1          1
          1          0
          1          1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)

In [34]:
y, X = patsy.dmatrices('v2 ~ key1 + 0', data)

X


DesignMatrix with shape (8, 2)
  key1[a]  key1[b]
        1        0
        1        0
        0        1
        0        1
        1        0
        0        1
        1        0
        0        1
  Terms:
    'key1' (columns 0:2)

In [35]:
y, X = patsy.dmatrices('v2 ~ key1 + key2', data)

X


DesignMatrix with shape (8, 3)
  Intercept  key1[T.b]  key2
          1          0     0
          1          0     1
          1          1     0
          1          1     1
          1          0     0
          1          1     1
          1          0     0
          1          1     0
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)

In [36]:
y, X = patsy.dmatrices('v2 ~ C(key1) + key2', data)

X

DesignMatrix with shape (8, 3)
  Intercept  C(key1)[T.b]  key2
          1             0     0
          1             0     1
          1             1     0
          1             1     1
          1             0     0
          1             1     1
          1             0     0
          1             1     0
  Terms:
    'Intercept' (column 0)
    'C(key1)' (column 1)
    'key2' (column 2)

In [37]:
y, X = patsy.dmatrices('v2 ~ C(key2)', data)

X

DesignMatrix with shape (8, 2)
  Intercept  C(key2)[T.1]
          1             0
          1             1
          1             0
          1             1
          1             0
          1             1
          1             0
          1             0
  Terms:
    'Intercept' (column 0)
    'C(key2)' (column 1)

In [38]:
data


key1  key2  v1   v2
0    a     0   1 -1.0
1    a     1   2  0.0
2    b     0   3  2.5
3    b     1   4 -0.5
4    a     0   5  4.0
5    b     1   6 -1.2
6    a     0   7  0.2
7    b     0   8 -1.7

In [39]:
data['key2'] = data['key2'].map({0: 'zero', 1: 'one'})

data

# When you are using multiple categorical variables, 
# it's often useful to create interaction terms of the form key1:key2
# This allows you to capture the combined effect of 
# the two variables on the response

# this is analysis of variance (ANOVA) models

key1  key2  v1   v2
0    a  zero   1 -1.0
1    a   one   2  0.0
2    b  zero   3  2.5
3    b   one   4 -0.5
4    a  zero   5  4.0
5    b   one   6 -1.2
6    a  zero   7  0.2
7    b  zero   8 -1.7

In [40]:
y, X = patsy.dmatrices('v2 ~ key1 + key2', data)

X

DesignMatrix with shape (8, 3)
  Intercept  key1[T.b]  key2[T.zero]
          1          0             1
          1          0             0
          1          1             1
          1          1             0
          1          0             1
          1          1             0
          1          0             1
          1          1             1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)

In [41]:
y, X = patsy.dmatrices('v2 ~ key1 + key2 + key1:key2', data)

X

DesignMatrix with shape (8, 4)
  Intercept  key1[T.b]  key2[T.zero]  key1[T.b]:key2[T.zero]
          1          0             1                       0
          1          0             0                       0
          1          1             1                       1
          1          1             0                       0
          1          0             1                       0
          1          1             0                       0
          1          0             1                       0
          1          1             1                       1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)
    'key1:key2' (column 3)

In [42]:
# 12.3 Introduction to statsmodels

# statsmodels is a powerful library for statistical modeling
# It provides classes and functions for estimating and 
# testing statistical models


import statsmodels.api as sm
import statsmodels.formula.api as smf


In [43]:
# Estimating Linear Models with statsmodels

# to make the example reproducible

rng = np.random.default_rng(seed=42)

def dnorm(mean, variance, size=1):
    if isinstance(size, int):
        size = (size,)
    return mean + np.sqrt(variance) * rng.standard_normal(*size)

N = 100

X = np.c_[dnorm(0, 0.4, size=N), 
          dnorm(0, 0.6, size=N),
          dnorm(0, 0.2, size=N)]
eps = dnorm(0, 0.1, size=N)
beta = [0.1 , 0.3, 0.5]

y = np.dot(X, beta) + eps


In [44]:
X[:5]

array([[ 0.19272   , -0.29292345,  0.15096793],
       [-0.6577437 ,  1.00637791,  0.62944502],
       [ 0.47462701, -0.27596089,  0.0405108 ],
       [ 0.59486536,  0.5712771 ,  0.28797818],
       [-1.233943  , -0.72317715, -0.91686484]])

In [45]:
y[:5]

array([ 0.55311503,  0.06581195,  0.25809624,  0.27096996, -0.81817232])

In [46]:
X_model = sm.add_constant(X)

X_model[:5]

array([[ 1.        ,  0.19272   , -0.29292345,  0.15096793],
       [ 1.        , -0.6577437 ,  1.00637791,  0.62944502],
       [ 1.        ,  0.47462701, -0.27596089,  0.0405108 ],
       [ 1.        ,  0.59486536,  0.5712771 ,  0.28797818],
       [ 1.        , -1.233943  , -0.72317715, -0.91686484]])

In [47]:
model = sm.OLS(y, X)

model

# the sm.OLS model is a linear regression model
# it estimates the relationship between the dependent 
# variable y and the independent variables X
# it does this by finding the best-fitting line
# through the data points in the scatter plot

In [48]:
results = model.fit()

results.params

# this is the estimated coefficients for the linear regression model
# the coefficients represent the change in the dependent variable y
# for a one-unit change in the independent variable X
# the intercept represents the expected value of y when all X variables are 0

array([0.15375095, 0.24337035, 0.4714836 ])

In [49]:
print(results.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.472
Model:                            OLS   Adj. R-squared (uncentered):              0.455
Method:                 Least Squares   F-statistic:                              28.87
Date:                Mon, 01 Sep 2025   Prob (F-statistic):                    2.00e-13
Time:                        07:55:28   Log-Likelihood:                         -26.830
No. Observations:                 100   AIC:                                      59.66
Df Residuals:                      97   BIC:                                      67.48
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [50]:
data = pd.DataFrame(X_model, columns=['const', 'feature1', 'feature2', 'feature3'])
data['target'] = y

data.head()

const  feature1  feature2  feature3    target
0    1.0  0.192720 -0.292923  0.150968  0.553115
1    1.0 -0.657744  1.006378  0.629445  0.065812
2    1.0  0.474627 -0.275961  0.040511  0.258096
3    1.0  0.594865  0.571277  0.287978  0.270970
4    1.0 -1.233943 -0.723177 -0.916865 -0.818172

In [51]:
results = smf.ols(formula='target ~ feature1 + feature2 + feature3', 
                  data=data).fit()
results.params

Intercept    0.033122
feature1     0.158127
feature2     0.243543
feature3     0.475920
dtype: float64

In [52]:
results.tvalues

# this is the t-values for the linear regression model
# the t-values represent the number of standard deviations
# the estimated coefficients are from 0
# a high absolute t-value indicates that the coefficient is significantly different from 0

Intercept    1.027075
feature1     2.395278
feature2     5.697896
feature3     6.753675
dtype: float64

In [53]:
results.predict(data[:5])

# these are the predicted values for the target variable
# the predicted values are obtained by applying 
# the fitted model to the input features

# the predicted values represent the model's estimate of the target variable
# the predicted values can be compared to 
# the actual values to assess the model's performance

# the closer the predicted values are to the actual values, 
# the better the model's performance

# the predicted values can be visualized using a scatter plot

# the scatter plot can show the relationship between 
# the predicted and actual values


0    0.064106
1    0.473777
2    0.060245
3    0.403372
4   -0.774477
dtype: float64

In [54]:
# Estimating Time Series Processes

init_x = 4

values = [init_x, init_x]
N=1000

b0 = 0.8
b1 = -0.4
noise = dnorm(0, 0.1, size=N)

for i in range(N):
    new_x = values[-1] * b0 + values[-2] * b1 + noise[i]
    values.append(new_x)




In [55]:
from statsmodels.tsa.ar_model import AutoReg

MAX_LAGS = 5

model = AutoReg(values, lags=MAX_LAGS)
results = model.fit()


In [56]:
results.params

array([-0.01017991,  0.87657024, -0.46656477,  0.07084574, -0.03970297,
       -0.00398814])

In [57]:
# 12.4 Introduction to Scikit-Learn
# Scikit-Learn is a powerful and widely-used machine learning library in Python. 
# It provides a range of supervised and unsupervised learning algorithms, 
# as well as tools for model evaluation and selection. In this section, 
# we will cover the basics of using Scikit-Learn for building and evaluating 
# machine learning models.

%pip install scikit-learn
import sklearn as skl

Note: you may need to restart the kernel to use updated packages.


In [58]:
# now-classic Titanic dataset from a Kaggle competition
# https://www.kaggle.com/c/titanic/data

# datasets.titanic/train.csv
# https://www.kaggle.com/datasets/hesh97/titanicdataset-traincsv

# datasets.titanic/test.csv
# https://www.kaggle.com/datasets/hesh97/titanicdataset-testcsv

# datasets.titanic/gender_submission.csv
# https://www.kaggle.com/datasets/hesh97/titanicdataset-gender_submissioncsv


In [59]:
train = pd.read_csv('train.csv')

test = pd.read_csv('titanic_test.csv')

train.head()


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [60]:
train.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [64]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [61]:
test.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
# In statistics and machine learning, a model is a 
# mathematical representation of a process or system that is
# used to make predictions or decisions based on data. 
# Models can take many forms,
# including linear equations, decision trees, and neural networks,
# and they can be trained on historical data to identify patterns and 
# relationships that can be used to inform future predictions.

# a typical task is to predict whether a passenger would survive or 
# not based on various features such as age, sex, and class.

# A model is fitted on a training dataset, and then evaluated on 
# a test dataset to assess its performance.

# The goal is to minimize the difference between the predicted and 
# actual outcomes,
# which is often measured using metrics such as accuracy, 
# precision, recall, and F1 score.

In [65]:
# Using age as a predictor

input_value = train['Age'].median()

train['Age'] = train['Age'].fillna(input_value)

test['Age'] = test['Age'].fillna(input_value)

In [ ]:
train['IsFemale'] = train['Sex'].apply(lambda x: 1 if x == 'female' else 0)
test['IsFemale'] = test['Sex'].apply(lambda x: 1 if x == 'female' else 0)

# Specify our models. I add a columns IsFemale as an encoded version of Sex

In [68]:
predictors = ['Pclass','IsFemale','Age']

x_train = train[predictors].to_numpy()
y_train = train['Survived'].to_numpy()

x_test = test[predictors].to_numpy()

In [69]:
x_train[:5]

array([[ 3.,  0., 22.],
       [ 1.,  1., 38.],
       [ 3.,  1., 26.],
       [ 1.,  1., 35.],
       [ 3.,  0., 35.]])

In [70]:
y_train[:5]

array([0, 1, 1, 1, 0])

In [71]:
# Using the LogisticRegression model and creating model instance

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(x_train, y_train)

LogisticRegression()


LogisticRegression()

In [73]:
y_predicted = model.predict(x_test)

y_predicted[:10]

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0])

In [77]:
# Accuracy on training set
y_train_predicted = model.predict(x_train)
(y_train == y_train_predicted).mean()

np.float64(0.7878787878787878)

In [79]:
# In practice, we would also want to evaluate our model on the test set
# Only run this if 'Survived' exists in test set
if 'Survived' in test.columns:
	y_test = test['Survived'].to_numpy()
	y_test_predicted = model.predict(x_test)
	accuracy = (y_test == y_test_predicted).mean()
	print("Test set accuracy:", accuracy)
else:
	print("Test set does not contain true labels ('Survived'), so accuracy cannot be computed.")

Test set does not contain true labels ('Survived'), so accuracy cannot be computed.


In [ ]:
# In practice there are often many additional layers of 
# complexity in model evaluation.

# Many models have parameters that can be tuned to improve performance.

# cross-validation is a technique used to assess how the results of a statistical 
# analysis will generalize to an independent data set.

In [80]:
from sklearn.model_selection import cross_val_score

model = LogisticRegression(C=10)
scores = cross_val_score(model, x_train, y_train, cv=5)

scores

array([0.7877095 , 0.78651685, 0.79213483, 0.7752809 , 0.79213483])

In [ ]:
# this session is focused on data wrangling
# there are many others dedicated to modeling and data science books

# Introduction to Machine Learning with Python by Andreas C. Müller and 
# Sarah Guido (O'Reilly)

# Python Data Science Handbook by Jake VanderPlas (O'Reilly)

# Data Science from Scratch by Joel Grus (O'Reilly)
# Python Machine Learning by Sebastian Raschka and Vahid Mirjalili (Packt)
# Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow by Aurélien Géron (O'Reilly)